### ISSUE TITLE
Statistic plugin

### ISSUE THREAD

**Issue by pyxiscloud** [mochi-mqtt/server#158]
Hi!
Thank you for this great alternative to EMQX!)
But is there any plugin to see Statstic about connected clients and their IDs ?
Thank you!

**Comment by mochi-co** [comment]
Hi @pyxiscloud !

This sounds like something that can be added! Are there any particular statistics/behaviour you'd like to see?

**Comment by pyxiscloud** [comment]
**- Main tab:** server uptime, server version
- connected clients, topics, subscribtions. Current value and max value from server start. 
- **Clients tab** (connected time, Id, username, protocol version, subscriptions count, current connetion status). Filter fields by client Id , username, protocol.
- **Settings tab ** - username/password to access this web page

**Comment by mochi-co** [comment]
Thanks @pyxiscloud - I've added this to the roadmap, we'll think about how to implement it in a nice way :)

**Comment by mochi-co** [comment]
This discussion is now located at https://github.com/orgs/mochi-mqtt/discussions/280#discussioncomment-6755593
