### ISSUE TITLE
Moving logger over from zerolog to slog

### ISSUE THREAD

**Issue by dgduncan** [mochi-mqtt/server#245]
Wanted to throw this out there before any work is done on my end. I have been following the development of [slog](https://pkg.go.dev/golang.org/x/exp/slog) and have been feeling that migrating over from zerolog -> slog could have a number of benefits, the two of which are moving to a something that will soon be in the standard lib and performance based logging (similar to zerolog) with no (or perhaps minimal I need to check on that) heap allocation logging. See [this](https://pkg.go.dev/golang.org/x/exp/slog#hdr-Performance_considerations) for considerations. As a fan of using the standard library for as many things as possible I do feel this would be a good standardization move as we move into the future. I know this is still technically in the experimental package; however, it will be moving to core in 1.21, see [here](https://tip.golang.org/doc/go1.21) for draft release notes.

**Comment by thedevop** [comment]
2nd that, I'm also a fan of using standard library. Maybe we should wait 2 months for it to become official with the API set in stone?

**Comment by mochi-co** [comment]
I **strongly** support moving to log/slog when it is available, the addition of zerolog was a painful consideration for me as it went against my attempts to make the code as flexible as possible - I'm not a fan of 'vendor lock-in'. With the exception of github.com/rs/xid, the code codebase is otherwise all standard library imports.

I think this is a wonderful idea.

**Comment by marang** [comment]
It would be a great feature to be able to use any logger, would be nice to be able to have an interface for a logger of our choice

**Comment by IshanDaga** [comment]
Would it also make sense to make this move and consider the OTEL part together ? We can have an OTEL collector externally pickup logs from STDOUT - left to the user to implement

**Comment by dgduncan** [comment]
@IshanDaga I have very little experience with OTEL; however, if you wish to contribute during/after I made the slog changes I think that would be awesome.

**Comment by IshanDaga** [comment]
Would love to - do tag the PR here when it's up, will branch out from that and add OTEL bits :)

**Comment by dgduncan** [comment]
@IshanDaga will do!

**Comment by dgduncan** [comment]
If anyone wants to follow the progress I have it up [here](https://github.com/dgduncan/mqtt/tree/feature/change-to-slog)

The right now there is actively two loggers so whomever wishes can compare the results.

**Comment by mochi-co** [comment]
@dgduncan I had a look, so far it's looking very nice 👍🏻 Great work :)

**Comment by thedevop** [comment]
This looks good @dgduncan! One feedback, although using LogAttrs is more performant, but using s.Slog.Info() is more readable:
1. `s.Slog.LogAttrs(context.TODO(), slog.LevelInfo, "mochi mqtt server started")` vs
2. `s.Slog.Info("mochi mqtt server started")`

**Comment by dgduncan** [comment]
@thedevop Indeed you are correct! I also agree that the `.Info` call is more readable. To give some context on why I chose to go with `LogAttrs`, I took the use of `zerolog` as a very intentional choice, i.e chosen for its' minimal allocation while logging. The closest thing that we have to that in `slog` is the use of `LogAttrs`, with the caveat that it may take a moment to grasp the signature of the call. With this in mind, I chose the `LogAttrs` route.

**Comment by dgduncan** [comment]
I believe I am done with the majority of the changes now if anyone is curious :)

**Comment by IshanDaga** [comment]
Hey! Looks great! I'll give push some stuff over the weekend, packed during this week

**Comment by mochi-co** [comment]
Fixed and released in [v2.4.0](https://github.com/mochi-mqtt/server/releases/tag/v2.4.0) - thank you very much for pushing this forward @dgduncan, you did a superb job and this is a great addition to the project.
