### ISSUE TITLE
Readme example broken

### ISSUE THREAD

**Issue by andrewbaxter** [mochi-mqtt/server#274]
At least... I think (sorry if this is way off base).  And before anything else, this is a really cool project!

It looks like `Serve` doesn't block, so the main function and therefore process exits immediately.

I just checked out main.go and I see conversely it calls `Serve` in a goroutine, is that necessary? https://github.com/mochi-mqtt/server/blob/main/cmd/main.go#L54

I'm guessing having serve not block is important because server implementations need to hook into signals to trigger a graceful shutdown?

**Comment by thedevop** [comment]
I just tried it, and it is running fine. The server is started in a Go routine, but immediately after that, there is <-done, and that channel will only receive something if SIGINT or SIGTERM is received.
https://github.com/mochi-mqtt/server/blob/0df69a4a4ecc98fb387e3dfbd20ad0627ae40e93/cmd/main.go#L54-L61

**Comment by dgduncan** [comment]
Having serve not block leaves us open to utilizing things such as signals without having to integrate it into something arbitrarily placed inside serve.

**Comment by torntrousers** [comment]
Still though on the subject of this issue, should the README example code be updated for that, something like just adding a few lines at the bottom so it waits and keeps the server up, eg - 
```
	// Run server until interupted
	exitSignal := make(chan os.Signal)
	signal.Notify(exitSignal, syscall.SIGINT, syscall.SIGTERM)
	<-exitSignal
```

**Comment by dgduncan** [comment]
@torntrousers I do see that you mean now and yes I agree that this is broken. I think that that example should more accurately reflect what is done in most/all of the other examples and use a go routine to run the server and have a channel that blocks till finished.

**Comment by dgduncan** [comment]
@andrewbaxter @torntrousers https://github.com/mochi-mqtt/server/pull/276
Let me know what y'all think. I believe this aligns way more with all of the other examples in the actual code base.

**Comment by andrewbaxter** [comment]
Yeah, sounds good to me!

**Comment by mochi-co** [comment]
This has been merged, nice update!! 👍🏻
