### ISSUE TITLE
[ask] Subscribe topic without create client

### ISSUE THREAD

**Issue by annlumia** [mochi-mqtt/server#277]
How to subscribe to certain topics directly without using MQTT Client anymore?

As for publishing messages, I can use 
```go
server. Publish(topic, payload, false, 0)
```

**Comment by werbenhu** [comment]
Are you suggesting that you want to subscribe to topics directly on the Mochi broker side? Why would there be a need to subscribe to topics on the server? If you have such a requirement, you can create your own hook plugin and handle the messages you want to subscribe to within the OnPublish() interface of the hook.

**Comment by annlumia** [comment]
I have such a need for an application I am developing, including to monitor the health status of microservices.

Hahaha, the hook seems to fit, I didn't think of it before, thanks for the suggestion.
