### ISSUE TITLE
connection keep alive time?

### ISSUE THREAD

**Issue by alexmengyuan** [mochi-mqtt/server#278]
Hello,
so I am testing mochi with mqtt.js, after connection is established, at server side it shows error like ```1006 unexpected EOF ``` for every 6 or 8 second, does the server have param for timeout for no message? do I have to send hearbeat message at application level? or is it just a l7 proxy related issue?
thanks

**Comment by werbenhu** [comment]
I think you can start by reading the MQTT protocol documentation. It's likely to contain the answers you're looking for. Whenever possible, try to find the answers on your own.[English](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html) [Chinese vertion](https://mcxiaoke.gitbooks.io/mqtt-cn/content/)

**Comment by mochi-co** [comment]
@alexmengyuan You can change the keepalive required in the client Connect packet (see https://github.com/mqttjs/MQTT.js/issues/230 for more info with mqtt.js). MQTTv5 also supports a 0 keepalive value, which will turn off keepalive checks altogether.

**Comment by alexmengyuan** [comment]
Thank your for the help, in the link shared, it seems that default keepalive is 60 sec while in my case it is kind of reconnect every 6 or 7 second, is there silimar param in server side? for mqtt.js, do I have to send ping package from client or server myself? thanks

**Comment by mochi-co** [comment]
@alexmengyuan Server side should respect whatever value is sent by the client 🤔 

With mqtt.js, you shouldn't need to send pings manually, as far as I am aware. Can you generate any logs on the client and server which might help diagnose the issue?

**Comment by werbenhu** [comment]
@alexmengyuan In your description above, I noticed that you mentioned using an L7 proxy. I think you can use the process of elimination to narrow down whether the issue lies in the MQTT server or the L7 proxy. Here are a few suggestions:

- You can create a simple TCP server yourself and place it on the same server as the MQTT server. Test to see if the connection also disconnects after 7 seconds.

- You can isolate the MQTT server, for example, deploy it on your local computer instead of on the server. Try accessing it through "localhost" and see if the connection still disconnects after 7 seconds.

In the above two steps, if Step 1 doesn't encounter any issues but Step 2 does, then the problem might be on the side of Mochi. If Step 1 encounters problems but Step 2 doesn't, then the issue might be with your L7 proxy.

**Comment by alexmengyuan** [comment]
Hi,
thank you for the advise, I build a simple server at local, start at localhost:1882, then connect in browser console ws://localhost:1882
from console's log it is behaves very similarly compare to what I am encountering at my production environtment,
e.g reconnect every 6 or 7 second,
is it possible that mochi server is not working well with mqtt.js when both side is at default configuration?

the error log at server side is like 

WRN error="websocket: close 1006 (abnormal closure): unexpected EOF" listener=ws1

server code is as below:
```
package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	mqtt "github.com/mochi-mqtt/server/v2"
	"github.com/mochi-mqtt/server/v2/hooks/auth"
	"github.com/mochi-mqtt/server/v2/hooks/debug"
	"github.com/mochi-mqtt/server/v2/listeners"
	"github.com/rs/zerolog"
)

func main() {

	sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigs
		done <- true
	}()

	server := mqtt.New(nil)
	l := server.Log.Level(zerolog.DebugLevel)
	server.Log = &l

	_ = server.AddHook(new(debug.Hook), &debug.Options{
		ShowPacketData: true,
	})
	_ = server.AddHook(new(auth.AllowHook), nil)

	ws := listeners.NewWebsocket("ws1", ":1882", nil)
	err := server.AddListener(ws)
	if err != nil {
		log.Fatal(err)
	}

	go func() {
		err := server.Serve()
		if err != nil {
			log.Fatal(err)
		}
	}()

	<-done
	server.Log.Warn().Msg("caught signal, stopping...")
	server.Close()
	server.Log.Info().Msg("main.go finished")
}
```

**Comment by werbenhu** [comment]
@alexmengyuan Can you provide the client code? It would be great if you could simplify it into a single-file demo.

**Comment by werbenhu** [comment]
mqttx offers a free online broker server at ws://broker.emqx.io with port number 8083. You can use your MQTT client to connect to this server and test if you encounter the same issue.

**Comment by alexmengyuan** [comment]
Hello,
the client code is pretty much looks like,
```
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <script src="./js/mqtt.min.js"></script>
  </body>
  <script>
    // execute when the DOM is fully loaded
    document.addEventListener('DOMContentLoaded', function () {
      // connect to MQTT broker
      var client = window.mqtt.connect('ws://localhost:1882');
    });
  </script>
</html>
```
and after connection is established, in browser console, it will shows 
```
mqtt connected
mqtt closed
```
repeatedly，
let me know if this can be reproduced,
thanks

**Comment by werbenhu** [comment]
I can't see a more complete version of the code you provided. Perhaps there's something missing in your server connection code. I would appreciate it if you could provide a complete code snippet. I can also consider your code for reference. I've tested my code and it's working fine. Additionally, connecting mqtt.js to Mochi is completely problem-free. You can also take a look at the more detailed demo I provided earlier in #273.
`
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>
  </body>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
        const options = {
            clean: true,
            connectTimeout: 4000,
            clientId: 'client_id',
        }
        const connectUrl = 'ws://localhost:1882/'
        const client = mqtt.connect(connectUrl, options);

        client.on("close", function () {
            console.log("Client has disconnected.....");
        });

        client.on("disconnect", function (packet) {
            console.log("Received a disconnect packet from the broker....." + packet);
        });

        client.on("connect", function (connack) {
            console.log("Successfully connected to the server" + new Date());
        });
    });
  </script>
</html>
`

**Comment by werbenhu** [comment]
This is a more comprehensive version that includes connection, topic subscription, and message publishing.
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- Input field for entering a message -->
    <input id="_message" width="300px" height="200px">
    <!-- Button to send the entered message -->
    <button id="_sendBtn">Send Message</button>
    <!-- Placeholder divs for displaying various status messages -->
    <div id="div1"></div>
    <div id="div2"></div>
    <div id="div3"></div>

    <!-- Include the MQTT library -->
    <script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>
    <script type="text/javascript">
        // When the DOM is loaded
        document.addEventListener("DOMContentLoaded", function () {
            // MQTT connection options
            const options = {
                clean: true,                 // Clean session
                connectTimeout: 4000,       // Connection timeout in milliseconds
                clientId: 'client_id',      // Client identifier
            };
            const connectUrl = 'ws://localhost:1882/';  // MQTT broker URL
            const client = mqtt.connect(connectUrl, options);  // Create MQTT client instance

            // DOM elements
            const div1 = document.getElementById("div1");
            const div2 = document.getElementById("div2");
            const div3 = document.getElementById("div3");
            const messageInput = document.getElementById("_message");
            const sendButton = document.getElementById("_sendBtn");

            // Handle reconnect event
            client.on('reconnect', () => {
                div1.textContent = "Reconnecting.....";
            });

            // Handle close event
            client.on("close", function () {
                div1.textContent = "Client has disconnected.....";
            });

            // Handle disconnect event
            client.on("disconnect", function (packet) {
                console.log("Received a disconnect packet from the broker....." + packet);
            });

            // Handle offline event
            client.on("offline", function () {
                div1.textContent = "Client is offline.....";
            });

            // Handle error event
            client.on("error", (error) => {
                div1.textContent = "Client encountered an error....." + error;
            });

            // Handle connect event
            client.on("connect", function (connack) {
                div1.textContent = "Successfully connected to the server" + new Date();
                client.subscribe("/test_topic", { qos: 0 });  // Subscribe to a topic

            });

            // Send button click event handler
            sendButton.addEventListener('click', function () {
                var message = messageInput.value;
                if (message == '') {
                    alert("Please enter the message to send");
                    return;
                }

                // Publish the message to a topic
                client.publish("/test_topic", message, { qos: 2 });
                div2.textContent = "Sent successfully";
                messageInput.value = "";
            });

            // Handle incoming message event
            client.on('message', (topic, message, packet) => {
                div3.textContent = "Client received a subscribed message, topic=" + topic + "; Message data:" + message + "; Data packet:" + packet;
            });

            // Handle window beforeunload event (when the user is leaving the page)
            window.addEventListener("beforeunload", () => {
                div1.textContent = "Client window closed, disconnecting";
                client.disconnect();  // Disconnect the MQTT client
            });
        });
    </script>
</body>

</html>
```

**Comment by werbenhu** [comment]
@alexmengyuan Any recent progress on this issue? If there are no further concerns, we will go ahead and close this issue.

**Comment by werbenhu** [comment]
After testing, it has been confirmed that the mqttjs connection to the Mochi server is working fine. Let's close the issue for now. If you encounter any further questions or issues related to this matter, please don't hesitate to reopen this issue.
