### ISSUE TITLE
Rapid deployment

### ISSUE THREAD

**Issue by zooyoyo** [mochi-mqtt/server#282]
Hi, what I want to ask is how to deploy a cluster, nginx?

**Comment by dgduncan** [comment]
@zooyoyo Would you mind elaborating on what you are looking for? Mochi-mqtt/server does not support clustering as it can only run single node. Are you referring to a cluster in that sense or do you mean simply deploying the broker?

**Comment by zooyoyo** [comment]
What I think is that Mochi mqtt/server itself has the ability to cluster, and currently can only alleviate some server pressure through proxies.

**Comment by dgduncan** [comment]
We currently do not support clustering. We have that marked in the roadmap but there is no support for clustering. The "closest" thing that may relieve pressure would be to have an LB with stick sessions and point towards an instance-group; however, I have never implemented such a thing so I can not speak to its' success

**Comment by zooyoyo** [comment]
Thank ！I have already seen the discussion about clusters and I will pay attention to it

**Comment by dgduncan** [comment]
@zooyoyo No worries and sounds good!

Closing as question has been answered.
