### ISSUE TITLE
When a MQTTv311 client tries to publish with qos2, and fails OnACLCheck, the client hangs forever and the connection stays open. Should we disconnect the client instead?

### ISSUE THREAD

**Issue by SimonMacIntyre** [mochi-mqtt/server#290]
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718042

> If a Server implementation does not authorize a PUBLISH to be performed by a Client; it has no way of informing that Client. It MUST either make a positive acknowledgement, according to the normal QoS rules, or close the Network Connection [MQTT-3.3.5-2].

I encountered this when testing my implementation and testing a `publish qos2` which `succesfully Connects (authenticates), but fails OnACLCheck`, in my case using Python Paho client 3.1.1, the publish fails but the client hangs forever on the publish. 

When I looked into the broker code it appears on failure of ACL check that it returns `nil` with no handling. 

Please let me know if I am missing anything or misinformed!

**Comment by SimonMacIntyre** [comment]
This case is the same using client of MQTTv5 too

**Comment by mochi-co** [comment]
I believe you are correct @SimonMacIntyre, this is a bug, at least for MQTTv3. If I remember, for v5 there is no provision to disconnect on ACL errors as some servers may wish to obscure their restrictions. I may be wrong though.

**Comment by SimonMacIntyre** [comment]
I'll take a quick peek! I see these in the v5 spec:
> The Client or Server sending the PUBACK packet MUST use one of the PUBACK Reason Codes [MQTT-3.4.2-1]
>The Client or Server sending the PUBREC packet MUST use one of the PUBREC Reason Code values. [MQTT-3.5.2-1]

Same  PUBACK reason code for both would be:
>135 | 0x87 | Not authorized | The PUBLISH is not authorized.

For qos0, it appears to be handled correctly!

**Comment by dgduncan** [comment]
So from reading that it seems like the spec for v3.1.1 should be to either ack and not publish or disconnect. A disconnect seems like the preferred solution as it makes it obvious there is a breach in the server rules; however, I can absolutely imagine a world in which a user of the server may not have control over some functionality of their MQTT client because it may be third part and a disconnection may make the server useless to them. Perhaps a capability could be in order to adjust functionality but that may just add unwanted complexity

**Comment by SimonMacIntyre** [comment]
Personally I lean towards the disconnect, over the ack and not publish. 

I do like the idea of in the future making that configurable in the file configuration, but maybe the disconnect is a reasonable path forward for now and if it becomes a problem for users we can explore making the server configurable on how to handle that only for v3.1.1?

**Comment by thedevop** [comment]
Created a PR #291 to address this.

The server will:

| | QOS 0 | QOS 1 | QOS 2 |
|-|:-:|:-:|:-:|
|MQTT v3| Ignore | Disconnect | Disconnect
|MQTT v3.1.1| Ignore | Disconnect | Disconnect
|MQTT v5| Ignore | Puback NotAuthorized | Pubrec NotAuthorized

**Comment by mochi-co** [comment]
This has been fixed and released in [v2.4.0](https://github.com/mochi-mqtt/server/releases/tag/v2.4.0). Thank you @thedevop!

**Comment by SimonMacIntyre** [comment]
While working on https://github.com/mochi-mqtt/server/issues/465, I noticed this code in receivePacket: https://github.com/SimonMacIntyre/mochi-server/blob/0e001765aa7840e7585f6ff5ac5edaf21bea0506/server.go#L524-L524

Given the discussion in this thread and the table showing how we forcefully disconnect `v3` clients when QoS1 or QoS2 messages fail ACL checks, but forego disconnecting v5 clients, it made me wonder: doesn't the current code in receivePacket mean we would disconnect a v5 client if any error with code >= 0x80 bubbles up? I suspect this might have been intended to handle [MQTT-3.2.2-7], but that specification only applies to CONNACK packets. Furthermore, doesn't it conflict philosophically with the result of this thread and PR which was merged?

Currently, we handle custom ACK requirements and packet processing no-ops in the various `processPublish, processX` family of functions, which still makes sense. However, I'm wondering if we should remove the s.disconnectClient code from receivePacket for two reasons:

*  It shouldn't disconnect v5 clients simply because of error codes, since v5 supports graceful error handling (as seen in the graceful errors returned for v5 QoS1/2 failures), what spec might this code be adhering to? Let me know if I am missing it or misunderstanding entirely.
*  If any disconnect logic is needed, it should probably be handled in the validateConnect logic instead and not as a catch-all in `receivePacket`, maybe?

Can someone provide a gut check on this? I'm still building my understanding of how the server architecture fits together, so please bear with me.

I can remove it without adding anything elsewhere if that's the change we need.
