### ISSUE TITLE
Discarding specific log messages with slog

### ISSUE THREAD

**Issue by dadebue** [mochi-mqtt/server#302]
We're deploying to AKS and there are a lot of "EOF" tcp connections coming from Kubernetes probing (we guess) leading to log warnings:
```
...
{"time":"2023-09-22T16:59:09.265775289Z","level":"WARN","msg":"","listener":"t1","error":"read connection: EOF"}
{"time":"2023-09-22T16:59:10.014990656Z","level":"WARN","msg":"","listener":"t1","error":"read connection: EOF"}
{"time":"2023-09-22T16:59:14.235740938Z","level":"WARN","msg":"","listener":"t1","error":"read connection: EOF"}
{"time":"2023-09-22T16:59:15.274348082Z","level":"WARN","msg":"","listener":"t1","error":"read connection: EOF"}
...
```

Before the move to slog we could discard those log messages with a custom hook:
```
func (h FilterHook) Run(e *zerolog.Event, level zerolog.Level, msg string) {
	if level == zerolog.WarnLevel && msg == "" {
		e.Discard()
	}
}
```
and
```
l := server.Log.Hook(hooks.FilterHook{})
server.Log = &l
```

Any idea how we can achieve this with the new slog logger? Or do you even have another idea where the EOF warnings are coming from?

Regards
Marco

**Comment by mochi-co** [comment]
These warnings occur when (typically) the server attempts to read after the client has already closed the connection. I think a more pertinent question here is whether we should even be logging this as a warning. My gut feeling is we probably shouldn't - or at least should move it to the debug scope - and we should potentially consider applying the same change for similar write errors.

Interested in what others think about this idea, or if anyone is relying on these messages (we could potentially add them as a server option if necessary, but good to know before making a change).

@dadebue I will have a think about how to solve your issue in the meantime 👍🏻

**Comment by dgduncan** [comment]
@dadebue This may be a bit of a heavy handed approach and would recommend testing this and experimenting with different approaches as I haven't experimented with custom handlers in production, but here is a way in which you could do this using a custom `slog.Handler`

```
type FilterHandler struct {
	h slog.Handler
}

func (h *FilterHandler) Enabled(ctx context.Context, level slog.Level) bool {
	return h.h.Enabled(ctx, level)
}

func (h *FilterHandler) WithAttrs(attrs []slog.Attr) slog.Handler {
	return &FilterHandler{h: h.h.WithAttrs(attrs)}
}

func (h *FilterHandler) WithGroup(name string) slog.Handler {
	return &FilterHandler{h: h.h.WithGroup(name)}
}

func (h *FilterHandler) Handle(ctx context.Context, r slog.Record) error {
	var drop bool
	r.Attrs(func(a slog.Attr) bool {
		if a.Key == "error" {
			if a.Value.String() == "read connection: EOF" {
				drop = true
			}
		}

		return !drop
	})

	if drop {
		return nil
	}

	return h.h.Handle(ctx, r)
}

func main() {
        logger := slog.New(&FilterHandler{
	        h: slog.NewJSONHandler(os.Stdout,
			        nil),
        })
}




```

**Comment by dgduncan** [comment]
@mochi-co I also have been thinking about this recently. I am a bit on the fence on what should be done as the error is indeed an `error`; however, many people have asked about this specific error and I think tends to distract more than anything. With that in mind I think I am leaning a but more towards the `DEBUG` route as it is indeed legitimate, but I think an `ERROR` level log should be reserved for things that are actively and negatively effecting server functionality or health.

**Comment by dadebue** [comment]
FYI: The mentioned solution works just fine. But I think that this error is more distracting then helpful too...

> @dadebue This may be a bit of a heavy handed approach and would recommend testing this and experimenting with different approaches as I haven't experimented with custom handlers in production, but here is a way in which you could do this using a custom `slog.Handler`
> 
> ```
> type FilterHandler struct {
> 	h slog.Handler
> }
> 
> func (h *FilterHandler) Enabled(ctx context.Context, level slog.Level) bool {
> 	return h.h.Enabled(ctx, level)
> }
> 
> func (h *FilterHandler) WithAttrs(attrs []slog.Attr) slog.Handler {
> 	return &FilterHandler{h: h.h.WithAttrs(attrs)}
> }
> 
> func (h *FilterHandler) WithGroup(name string) slog.Handler {
> 	return &FilterHandler{h: h.h.WithGroup(name)}
> }
> 
> func (h *FilterHandler) Handle(ctx context.Context, r slog.Record) error {
> 	var drop bool
> 	r.Attrs(func(a slog.Attr) bool {
> 		if a.Key == "error" {
> 			if a.Value.String() == "read connection: EOF" {
> 				drop = true
> 			}
> 		}
> 
> 		return !drop
> 	})
> 
> 	if drop {
> 		return nil
> 	}
> 
> 	return h.h.Handle(ctx, r)
> }
> 
> func main() {
>         logger := slog.New(&FilterHandler{
> 	        h: slog.NewJSONHandler(os.Stdout,
> 			        nil),
>         })
> }
> ```

**Comment by dgduncan** [comment]
Closing issue.
