### ISSUE TITLE
Is 'vendor' still necessary?

### ISSUE THREAD

**Issue by werbenhu** [mochi-mqtt/server#314]
Since we now require Go version 1.21, do we still need to include the 'vendor' directory in the repository? If users need the 'vendor' directory, they can generate it themselves using 'go mod vendor'.

**Comment by mochi-co** [comment]
Previously when we discussed this the consensus was that packaging the vendor directory ensures the code will always work even if the dependancies are unavailable for whatever reason (i.e. an environment with no internet). Interested to know how others feel about this and if it's still applicable.

**Comment by dgduncan** [comment]
My experience with vendoring has always been as a necessary evil when working with internal dependencies that are unable to be pulled in other environments while building. I have seen it become an issue when code bases get large and the vendor folder becomes unwieldy to commit. I have no strong opinion either way especially when it is as small as this folder is.

I would love to hear if others have a stronger opinion, but I find no harm in continuing with the status quo as I do not have an example that un-commiting the vendor folder would have any strong benefit outside of cleaning up our git.

**Comment by werbenhu** [comment]
I think deploying in an environment without internet access shouldn't be a problem. Users should first be able to fetch this repo from GitHub, and if they can do that, they should certainly be able to fetch others. 'The dependencies are unavailable' might be a good reason for this.

**Comment by werbenhu** [comment]
@dgduncan @mochi-co I think that deploying in an environment without internet access shouldn't pose a problem. Users should first be able to fetch this repository from GitHub, and if they can do that, they should certainly be able to fetch others. 'The dependencies are unavailable' might be a valid reason for this.

Perhaps we can weigh the pros and cons:

#### Pros:

- Dependencies are unavailable, but we can still compile and run without any issues.
#### Cons:

- It may result in additional code.
- There might be a need for frequent updates to the Vendor library, which we may not actually be concerned about.

Additionally, we should assess how likely it is to encounter the 'dependencies are unavailable' scenario. From my experience, most of the repositories I've come across on GitHub do not include the vendor directory in their repository.

**Comment by mochi-co** [comment]
As for me, I am quite happy to remove the vendor folder, but I would be interested to hear from others like @thedevop and @torntrousers as they often have interesting use cases.

**Comment by thedevop** [comment]
I don't have strong preference, leaning slightly for removing.

**Comment by dgduncan** [comment]
It seems to me that there is more interest in removing vendor, or at least giving it a go!

**Comment by mochi-co** [comment]
Merged into master :)
