### ISSUE TITLE
Developers (core) Team

### ISSUE THREAD

**Issue by mochi-co** [mochi-mqtt/server#317]
@werbenhu was able to show me how to actually add people to the organisation, which is something I had totally misunderstood and missed. This should be corrected now, so anyone who was formerly a collaborator should have received an invitation to join the organisation. This should provide you with elevated access permissions - use wisely 🙂  

The new process flow will look a little something like this: 
* Express interest in the project and assist with some PRs/issues -> become an outside collaborator.
* Continue this for a while and help improve the project in some way -> be added to @mochi-mqtt/developers team (and/or another team if you have a particular interest).

I'll leave this issue open for a little while so people can see it.

**Comment by werbenhu** [comment]
@mochi-co I think it's best to retain the merge rights for you alone. Ultimately, the final code review still needs to be done by you.

**Comment by mochi-co** [comment]
@werbenhu You're not the only person to say this to me, so my guess is it would make everyone feel more comfortable. I've set everyone to `triage` role - which is read and some issue management capabilities. You'll have to advise me if it's not working as expected :)

**Comment by mochi-co** [comment]
@werbenhu @dgduncan I'm not sure this is working correctly, so any advice would be appreciated.

**Comment by werbenhu** [comment]
@mochi-co I still don't have the permission to edit the code when I review some code, which also means I don't have the permission to submit code to the forked branch.

**Comment by mochi-co** [comment]
@werbenhu I've given everyone write access again, but offset this by adding a new branch rule that restricts merging to admins, and I've set the number of required approvals to 6+. I have no idea if this will work though, as I can't see it from outside of my own account...

**Comment by werbenhu** [comment]
@mochi-co it's working. I can proceed with the submission. Thanks.
