### ISSUE TITLE
Very nice work, will this repo keep maintained?

### ISSUE THREAD

**Issue by lucasjinreal** [mochi-mqtt/server#328]
I saw there are many Mqtt broker in Golang are not maintained any longer, just let developers keep migrating one lib to another, no of them really solves all problems especially on extremely complicated use cases.

For example, using mqtt5 as a IM server protocol.

I just wonder:

1. will mochi-mqtt server keep maintenance?
2. does it able to use as a IM server protocol? Not just pub/sub, but some complicated usage, such as internal publish message, auth (plugin or callback etc).
3. Does it support message inceptors? Any demos?

If so, I would like contribute a Mqtt client based on Flutter, so that develops not only can use this broker in Python/Golang, but also any other platforms. Especially make it useful in IM field.

**Comment by dgduncan** [comment]
@lucasjinreal 

1. At the moment there is no talks of dropping support for the broker. We have multiple contributors what all use it quite extensively in a variety of industries and usecases
2. I am unfamiliar with what an IM protocol is. The hooks system is quite powerful and can be used for custom integrations such as pubsub and other things.
3. The broker uses `hooks` that allow custom integrations. Please look [here](https://github.com/mochi-mqtt/server/blob/main/examples/hooks/main.go) if you are interested. We also started a new [repository ](https://github.com/mochi-mqtt/hooks)that will contain some more extensive hooks. For example. the one in PR right now is an HTTP auth hook
