### ISSUE TITLE
Can not close example with ctrl + c

### ISSUE THREAD

**Issue by lucasjinreal** [mochi-mqtt/server#329]
sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)

	signal.Notify(sigs, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigs
		done <- true
	}()

	// Create the new MQTT Server.
	server := mqtt.New(&mqtt.Options{
		InlineClient: true,
	})

why not work

**Comment by torntrousers** [comment]
You're not showing complete code so having to guess - you need ```<-done``` somewhere?

Here's a minimal example - 
```
package main

import (
	"os"
	"os/signal"
	"syscall"

	mqtt "github.com/mochi-mqtt/server/v2"
)

func main() {
	sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigs
		done <- true
	}()

	server := mqtt.New(nil)

	go func() {
		err := server.Serve()
		if err != nil {
			server.Log.Error("Server error", err)
		}
	}()

	<-done
	server.Log.Warn("caught signal, stopping...")
	_ = server.Close()
	server.Log.Info("main.go finished")
}
```

**Comment by lucasjinreal** [comment]
I need to call server.Close()? I for get this line seems

**Comment by dgduncan** [comment]
Exactly what @torntrousers said.

**Comment by thedevop** [comment]
@lucasjinreal, did the above resolve issue? Can this issue be closed?
