### ISSUE TITLE
How to call server.Publish() inside a hook? 如何在hooks的函数里面直接使用server.Publish()?

### ISSUE THREAD

**Issue by lucasjinreal** [mochi-mqtt/server#330]
例如在OnConnectAuth中，登录成功后，返回一个联系人列表，我的hooks写在单独的文件，如何调用server.Publish呢？会存在一个辅助类调用main 变量的问题，难道要把server变成一个global?

**Comment by werbenhu** [comment]
你在调用server.AddHook()时，不是有一个Option的选项吗，你可以将server传入到option里面，然后在Hook里面使用穿进去的server应该可以的。

**Comment by werbenhu** [comment]
@lucasjinreal 已经更新的example中的示例怎么使用，参考：https://github.com/mochi-mqtt/server/blob/main/examples/hooks/main.go
