### ISSUE TITLE
invalid client status which loaded from storage.

### ISSUE THREAD

**Issue by x20080406** [mochi-mqtt/server#339]
Hi, there
     When invoke the the method `client.Closed()` with client loaded from storage, but the client not reconnect to server . it still  return false.  I think there should invoke the `client.Stop` at the end of `server.loadClients`

```go
// loadClients restores clients from the datastore.
func (s *Server) loadClients(v []storage.Client) {
	for _, c := range v {
		cl := s.NewClient(nil, c.Listener, c.ID, false)
		cl.Properties.Username = c.Username
		cl.Properties.Clean = c.Clean
		cl.Properties.ProtocolVersion = c.ProtocolVersion
		cl.Properties.Props = packets.Properties{
			SessionExpiryInterval:     c.Properties.SessionExpiryInterval,
			SessionExpiryIntervalFlag: c.Properties.SessionExpiryIntervalFlag,
			AuthenticationMethod:      c.Properties.AuthenticationMethod,
			AuthenticationData:        c.Properties.AuthenticationData,
			RequestProblemInfoFlag:    c.Properties.RequestProblemInfoFlag,
			RequestProblemInfo:        c.Properties.RequestProblemInfo,
			RequestResponseInfo:       c.Properties.RequestResponseInfo,
			ReceiveMaximum:            c.Properties.ReceiveMaximum,
			TopicAliasMaximum:         c.Properties.TopicAliasMaximum,
			User:                      c.Properties.User,
			MaximumPacketSize:         c.Properties.MaximumPacketSize,
		}
		cl.Properties.Will = Will(c.Will)
                cl.Stop(packets.ErrServerShuttingDown) // make it stopped
		s.Clients.Add(cl)		
	}
}
```

Another option. I think there should add a `connected` int64 for `ClientState`.

Thank you.

**Comment by thedevop** [comment]
@x20080406 , good find! It is a bug, as a new context is created with newClient, but it is not canceled as there is no disconnect activity. What you proposed would work, I would move it up to immediately after creating the new client though.
```go
		cl := s.NewClient(nil, c.Listener, c.ID, false)
		cl.Stop()
```

**Comment by werbenhu** [comment]
@thedevop I think moving `go cl.WriteLoop()` out of NewClient() and placing it in either server.EstablishConnection() or server.attachClient() would be more reasonable.

**Comment by thedevop** [comment]
We can add a new condition check that if c net.Conn is nil, don't start the WriteLoop.

**Comment by thedevop** [comment]
Just saw your PR, it's more elegant.

**Comment by thedevop** [comment]
@werbenhu, for those clients that doesn't SessionExpiryIntervalFlag == 0, or have cl.Properties.Clean == true, we still have to stop these clients. In Stop, in addition to cancel the context, it also stores the disconnected time. This value is used to determine if a client has expired.
