### ISSUE TITLE
consume very slow when Inflights to many

### ISSUE THREAD

**Issue by VinsonWood** [mochi-mqtt/server#340]
Hello, I am using Mochi to test offline messages. I have two clients subscribing to the same topic with a QoS of 1, and both have clean session turned off. This topic continuously receives QoS 1 data. When one of the clients disconnects, the Inflight for that client keeps accumulating, causing a continuous increase in memory usage. When the memory consumption reaches around 300-400 MB, the other connected client can only consume messages at an extremely slow rate, far below the sending rate of this topic. If the disconnected client reconnects, the Inflight and memory will be released, and memory consumption will reduce. At this point, the consumption rate will return to normal.
I know that I can use a hook to limit the size of the Inflight and, after the client disconnection, I can check the size of the client's Inflight to clear it. Are there any other elegant solutions available?

**Comment by thedevop** [comment]
@mochi-co , currently we store all QoS > 0 messages. Even if receive quota is exceeded:
https://github.com/mochi-mqtt/server/blob/624dde0986e28442a1406145de637c835190b10d/server.go#L971-L993

With Expiry = -1, it also appears the message will never be removed from Inflight.

Perhaps we can make the following changes:

**Comment by thedevop** [comment]
I benchmarked pk.Properties.Encode using the following:

```go
func BenchmarkEncodeNoPool(b *testing.B) {
	props := propertiesStruct

	for i := 0; i < b.N; i++ {
		buf := bytes.NewBuffer([]byte{})
		props.Encode(Reserved, Mods{AllowResponseInfo: true}, buf, 0)
		_ = buf
	}
}

func BenchmarkEncodePoolBuf(b *testing.B) {
	props := propertiesStruct

	for i := 0; i < b.N; i++ {
		buf := mempool.GetBuffer()
		props.Encode(Reserved, Mods{AllowResponseInfo: true}, buf, 0)
		mempool.PutBuffer(buf)
	}
}
```

The results are:
```
cpu: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
BenchmarkEncodeNoPool-8    	  664742	      1716 ns/op	     736 B/op	       9 allocs/op
BenchmarkEncodePoolBuf-8   	  748135	      1574 ns/op	     504 B/op	       6 allocs/op
```

If I also replace the buf within Encode to use buffer pool, the results are:
```
cpu: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
BenchmarkEncodeNoPool-8    	  730120	      1552 ns/op	     288 B/op	       6 allocs/op
BenchmarkEncodePoolBuf-8   	  873458	      1352 ns/op	      56 B/op	       3 allocs/op
```

**Comment by thedevop** [comment]
@mochi-co , PR #359 adds the ability to config maximum QoS > 0 message to store, which also means none of the clients send quota will exceed this value.

In the process, I found few additional potential issues:
1. Publish QoS > 0 message to the same topic, can be sent out of order. Here are the steps:
   1. Publish message A to client, cl.State.Inflight.sendQuot  == 0, the message will be stored, but no attempt will be made to send it until client reconnect
   2. Received ack from client for previously sent message, so cl.State.Inflight.sendQuot is now > 0
   3. Publish message B to client, now the broker will store the message and immediately send the message 

   To address this, we can add a list (FIFO) to the client which tracks all the QoS > 0 messages that were not sent once. This list will not be inherited on new connections. When any publishing to this client, it will drain the list (may have additional trigger) before any attempt to send more QoS > 0 messages. 
2. We need to protect packetID 0 or only delete Inflight if QoS > 0
https://github.com/mochi-mqtt/server/blob/65c78534dcb5861dc8ea2163ac58ce603b6e9881/server.go#L999-L1008
3. With this PR, if message to be stored is > MaximumInflight, s.Info.InflightDropped is incremented, and logged, should we call OnQosDropped (but the message was never stored, so OnQosPublish was never called)
4. asdf

**Comment by thedevop** [comment]
@VinsonWood , you can now config maximum inflight messages (Capabilities.MaximumInflight) per client in v2.4.6. Please let us know if it solves your issue.

**Comment by VinsonWood** [comment]
@thedevop 
Thank you! let me try it.

**Comment by VinsonWood** [comment]
@thedevop  it works,thank you !
