### ISSUE TITLE
Packet encoding optimization

### ISSUE THREAD

**Issue by thedevop** [mochi-mqtt/server#342]
@mochi-co, I found some optimization opportunities when encoding packets:
1. During PublishEncode, write pk.Payload only once instead of twice
2. Use a memory pool (sync.Pool) for Buffer used during encodings

Lastly, in pk.Properties.Encode, a new Buffer is allocated:
https://github.com/mochi-mqtt/server/blob/624dde0986e28442a1406145de637c835190b10d/packets/properties.go#L197-L202

However in all instances where this function is called, a new Buffer is already allocated specifically for this: 
https://github.com/mochi-mqtt/server/blob/624dde0986e28442a1406145de637c835190b10d/packets/packets.go#L612-L616

Should we remove the NewBuffer within pk.Properties.Encode and use the Buffer that is passed in. This will also rsult in one less write of the property.

**Comment by mochi-co** [comment]
Released in v2.4.4 🚀
