### ISSUE TITLE
Version is "2.4.1" while the package version is v2.4.3

### ISSUE THREAD

**Issue by gpayer** [mochi-mqtt/server#350]
In line 29 in server.go there is this line:

`Version                       = "2.4.1" // the current server version.`

However this is not the current version and it makes for a very confusing log output during startup.

**Comment by mochi-co** [comment]
This is my fault, I'll correct it this evening. 

I'll try to catch up with everything else too - it's been a bit of a busy year!

**Comment by mochi-co** [comment]
Fixed in v2.4.4 :)
