### ISSUE TITLE
遍历Clients时如何判断当前Client是否为Disconected状态

### ISSUE THREAD

**Issue by liwei0705** [mochi-mqtt/server#366]
我看到有disconected字段记录断开的时间戳，但这个变量是私有的无法从外部读取。

是否代码中有我还没有注意到的地方？

**Comment by werbenhu** [comment]
参考这个[example](https://github.com/mochi-mqtt/server/blob/main/examples%2Fhooks%2Fmain.go)，可以网hook里面传值的。

**Comment by liwei0705** [comment]
> @liwei0705 你说的是Client.State.disconnected吗？这个字段是用来保存断开连接的时间，用这个来判断是否断开连接可能不太合适。建议你根据Clinet.Net.Conn来判断，先判断其为不为空，如果不为空，则判断下这个net.Conn是否是closed.

Thanks. Conn的判定也比较复杂，所以我改用OnDisconnect Hook + 自定义Map处理了...

**Comment by werbenhu** [comment]
这样更好，尽量让hook和server不要耦合在一起。
