### ISSUE TITLE
Hi, what is the simplest way to make messages can be restored when server cut off?

### ISSUE THREAD

**Issue by luohao123** [mochi-mqtt/server#369]
Currently the messages that not sent to client yet will be wiped out when server down.

I previous using badge, but that very terriable, causing about 5GB trash don't know what's file to my server, almost make my server bumm out.

Can just make offline message restore be an default behavior? Really need it!

**Comment by werbenhu** [comment]
@luohao123 Since most of our developers lack experience using BadgerDB as persistent data in a production environment, take a look at the configuration modifications and the addition of garbage collection described in #370 to see if they would be helpful for your use of BadgerDB.

**Comment by werbenhu** [comment]
@luohao123 Could you please check if version v2.6.0 resolves this issue?

**Comment by luohao123** [comment]
It's not work , dude.

**Comment by werbenhu** [comment]
@luohao123 The latest progress is discussed here: #375

**Comment by werbenhu** [comment]
@luohao123 Could this issue be closed?

**Comment by werbenhu** [comment]
The issue has been resolved, and due to the lack of feedback over an extended period, we are closing this issue. If there are any further problems, please reopen it.
