### ISSUE TITLE
[badgerdb] vlog growing unbounded - consider adding GC and exposing options

### ISSUE THREAD

**Issue by woodzy** [mochi-mqtt/server#370]
I noticed that BadgerDB storage started growing unbounded (it was many files and several gigabytes quite quickly). Looks like the Badgerhold/Badger Storage example doesn't provide a way for the user to utilize GC correctly per Badgers docs. https://github.com/dgraph-io/badger/blob/main/db.go#L1225

Fairly sure the option tuning is probably useful to expose as well somehow -- for example ValueLogFileSize has a [pretty large default](https://github.com/dgraph-io/badger/blob/6acc8e801739f6702b8d95f462b8d450b9a0455b/options.go#L180)

I didn't plumb up a full fix, just copied the default and started experimenting, but this showed that something like option tuning and GC can resolve the infinite growth modified a copy of the default to include some signalling and a regular GC call.

I would recommend at least adding the GC as a default. I would also suggest lowering some of the default or exposing them.

```
        go func() {
                ticker := time.NewTicker(5 * time.Minute)
                defer ticker.Stop()
                for { 
                        select {
                                case <- ticker.C:
                                        _ = h.db.Badger().RunValueLogGC(0.7)
                                        continue
                                case <- h.doneCh:
                                        return
                        }
                }
        }()
```

**Comment by werbenhu** [comment]
I've checked the official documentation of Badger regarding [garbage collection](https://dgraph.io/docs/badger/get-started/#garbage-collection). @woodzy , you're right. Since neither of us has experience using BadgerDB in a production environment, if you could, it would be great if you could submit a PR. This would be very helpful for most users who use BadgerDB as a persistent database.

**Comment by werbenhu** [comment]
@woodzy Can this #371 fix the issue?

**Comment by woodzy** [comment]
Thanks! These look like better implementations of my local workarounds during experimentation.

**Comment by mochi-co** [comment]
This should be fixed in `v2.6.0` - please let us know!

**Comment by OpenJarvisAI** [comment]
<img width="512" alt="image" src="https://github.com/mochi-mqtt/server/assets/136460643/2b847461-aeec-4cac-ab79-1cc352d30017">

It not fix, still growing on mem

**Comment by werbenhu** [comment]
@woodzy @OpenJarvisAI Could this issue be closed?

**Comment by werbenhu** [comment]
The issue has been resolved, and due to the lack of feedback over an extended period, we are closing this issue. If there are any further problems, please reopen it.
