### ISSUE TITLE
The badge still getting vlog file keep growing infirnity

### ISSUE THREAD

**Issue by OpenJarvisAI** [mochi-mqtt/server#374]
Please make sure 2.6.0 work on yourself side befrorelet users upgrade.

**it NOT WORK***@@@@!!!!!

**Comment by OpenJarvisAI** [comment]
Didn't do anything ,just started the sever and this file keeps growwing....

**Comment by werbenhu** [comment]
@OpenJarvisAI I'm really sorry. I might know where the issue is. I'll make time to fix and test it as soon as possible.

**Comment by werbenhu** [comment]
@OpenJarvisAI The latest progress is discussed here: #375

**Comment by werbenhu** [comment]
@OpenJarvisAI Could this issue be closed?

**Comment by werbenhu** [comment]
The issue has been resolved, and due to the lack of feedback over an extended period, we are closing this issue. If there are any further problems, please reopen it.
