### ISSUE TITLE
How to send topics posted by specific users only to specific subscribed users?

### ISSUE THREAD

**Issue by leijux** [mochi-mqtt/server#377]
The location of the hook:

https://github.com/mochi-mqtt/server/blob/47162a3770a38567230d28bbc79477a5c95aceb2/server.go#L1006

Use scenario: 

used to realize the filtering of clients, so that packets are forwarded only to clients that meet the conditions

My current solution:

use OnPacketEncode to filter clients. For clients that do not meet the conditions, I set the FixedHeader.Type field of the packet to packets.WillProperties. However, this approach results in recording error errors.

```go
func (h *Hook) OnPacketEncode(cl *mqtt.Client, pk packets.Packet) packets.Packet {
	switch {
	case pk.TopicName != topicSet && pk.TopicName != topicSetResp:
		return pk
	case pk.Origin == "":
		return pk
	case pk.FixedHeader.Type != packets.Publish:
		return pk
	}
	if pk.TopicName == topicSet && pk.Origin != "mqtt_"+cl.ID { 
		pk.FixedHeader.Type = packets.WillProperties
		return pk
	}
	return pk
}
```

**Comment by werbenhu** [comment]
@leijux If I understand correctly, you want to add some special tags while parsing the packet, so that you can filter them based on these tags during packet processing, right?

If that's the case, I suggest you store your own tag information in cl.Properties.Props.User. Here, you can save some Key-Value data.

**Comment by leijux** [comment]
> @leijux If I understand correctly, you want to add some special tags while parsing the packet, so that you can filter them based on these tags during packet processing, right?
> 
> If that's the case, I suggest you store your own tag information here in `cl.Properties.Props.User`, where you can save some Key-Value data for those users you want to filter.

用户属性可以作为筛选条件，但是我不知道如何在数据包转发阶段对转发行为进行控制。如下图，主题中有三个客户端，我只想将数据发送给其中的某个客户端，我当前的实现是使用 OnPacketEncode hook 函数，将 包的 FixedHeader.Type 设置为无效的类型，让数据包无法转发出去，但是这样会引发 error 错误，有没有更好的办法，感谢。

![image](https://github.com/mochi-mqtt/server/assets/40145943/053ba851-ef90-4d54-83de-503fa9b1b8a3)

**Comment by werbenhu** [comment]
@leijux 你这种的话，实现hook.OnACLCheck就行了

**Comment by leijux** [comment]
> @leijux 你这种的话，实现hook.OnACLCheck就行了，OnACLCheck会在发送给每个订阅者之前进行鉴权。

https://github.com/mochi-mqtt/server/blob/6b3b30e41280185c07fa92564d6901d133eae4d6/server.go#L1011

OnACLCheck 能控制是客户端是否有权限读取这个主题，但是我获取不到是谁发出的数据包，相同主题有时数据包可能要发送给client1，有时可能要发送给client2。

**Comment by werbenhu** [comment]
那你只能自己做一些改动了，自己增加一个类似OnACLCheck的钩子方法，然后可以把发送者的信息（比如ID）放到pk.Properties，OnACLCheck里面传递的不是topic，而是整个pk。

**Comment by leijux** [comment]
> 那你只能自己做一些改动了，自己增加一个类似OnACLCheck的钩子方法，比如OnSendToSubscriber，然后可以把发送者的信息（比如ID）保存到pk.Properties里面，将OnACLCheck的参数修改一下。传递的不是topic，而是整个pk。

感谢，我能在下发的位置增加一个hook函数并提交合并请求吗？

https://github.com/mochi-mqtt/server/blob/47162a3770a38567230d28bbc79477a5c95aceb2/server.go#L1006

**Comment by werbenhu** [comment]
@leijux 非常可以。

**Comment by leijux** [comment]
> @leijux 非常可以。我建议增加一个类似OnSendToSubscriber的钩子方法。类似鉴权，不过这个鉴权只针对发送给订阅者时。

好的，我来考虑实现它。😊

**Comment by werbenhu** [comment]
@leijux 我想了下，是不是可以将OnSendToSubscriber和onAclCheck合并会更好，只需要改变OnAclCheck的参数改变可以了

**Comment by leijux** [comment]
> @leijux 我又琢磨了下，是不是可以将OnSendToSubscriber和onAclCheck合并会更好，只需要OnAclCheck的参数改变就可以了，这样就没必要多出一个hook方法，逻辑也更明了

是一个更好的办法，但是会影响api的兼容性。

**Comment by leijux** [comment]
The cost of changing onAclCheck is still too high. It's possible to use a specific topic to forward to the corresponding clients.

```go
type Hook struct {
             ......
	clients *mqtt.Clients //Introducing mqtt.Clients at Init
}


func (h *Hook) OnPublish(cl *mqtt.Client, pk packets.Packet) (packets.Packet, error) {
	if pk.TopicName != "/a/b/c" {
		return pk, nil
	}
	id := string(pk.Payload)
	if client, ok := h.clients.Get(id); ok {
		client.WritePacket(packets.Packet{
			FixedHeader: packets.FixedHeader{Type: packets.Publish},
			TopicName:   "/x/y/z",
			Payload:     nil,
		})
	}
	return pk, nil
}
```
