### ISSUE TITLE
Does peddle perssistant released?

### ISSUE THREAD

**Issue by lucasjinreal** [mochi-mqtt/server#380]
Does peddle perssistant released?

**Comment by mochi-co** [comment]
Hi @lucasjinreal - Pebble has been added in v2.6.1

**Comment by lucasjinreal** [comment]
thanks, does the cache size unbounded issue has been tested for now?

**Comment by werbenhu** [comment]
@lucasjinreal What kind of tests are you referring to? You can refer to test #375 here. Additionally, the test coverage of Pebble is 100%, you can also check hooks/storage/pebble/pebble_test.go.

**Comment by lucasjinreal** [comment]
Will the cache size still unbounded? Meanwhile, just wonder how to enable it any tutorial about this?

**Comment by werbenhu** [comment]
Please refer to the instructions about Pebble in the readme.

>#### Pebble DB
>There's also a Pebble Db storage hook if you prefer file-based storage. It can be added and configured in much the same way >as the other hooks (with somewhat less options).
>```go
>err := server.AddHook(new(pebble.Hook), &pebble.Options{
>  Path: pebblePath,
> Mode: pebble.NoSync,
>})
>if err != nil {
>  log.Fatal(err)
>}
>```
>For more information on how the pebble hook works, or how to use it, see the [examples/persistence/pebble/main.go]>(examples/persistence/pebble/main.go) or [hooks/storage/pebble](hooks/storage/pebble) code.
