### ISSUE TITLE
MQTTX cannot use Topic Alias. MQTT5.0 主题别名发送卡住，无法发布主题别名的消息

### ISSUE THREAD

**Issue by kason111999** [mochi-mqtt/server#381]
MQTTX 测试
![image](https://github.com/mochi-mqtt/server/assets/126460104/3acf0564-9c3f-4ec8-b02d-96375cd086d7)

**Comment by werbenhu** [comment]
你用这个 https://github.com/eclipse/paho.mqtt.testing/blob/master/interoperability/client_test5.py 测试看看服务端是不是有问题，有没有可能是MQTTX客户端的问题？

**Comment by werbenhu** [comment]
As the issue is non-reproducible and no feedback has been received for a long time, it is now closed. If further problems arise, please reopen it.
