### ISSUE TITLE
Reload auth fIle on the run

### ISSUE THREAD

**Issue by leandrofars** [mochi-mqtt/server#384]
Nowadays It's possible to use a file for authentication, I would like changes to this file to be tied on the run, without the need to restart mqtt server, is it possible?

**Comment by werbenhu** [comment]
You can implement your own hook, where you can define rules within the `OnConnectAuthenticate` interface. Here, you can customize rules, which can be dynamic.

**Comment by leandrofars** [comment]
@werbenhu Thank you for the explanation!
