### ISSUE TITLE
Proposal: Add an Example for Custom Hook Usage

### ISSUE THREAD

**Issue by TheRiseOfDavid** [mochi-mqtt/server#407]
Hi,

I really like this project and I would love to contribute to it. I noticed there isn't an example for using custom hooks, which made it challenging for me to figure out the correct way to implement them. I believe other newcomers might face similar difficulties.

To address this, I would like to add an example demonstrating how to use custom hooks.

Could you please guide me on how to submit to update the README.md by pull request accordingly?

Thank you!

Maybe the example like 
hook.go
```go
type authHook struct {
	mqtt.HookBase
}

func (h *authHook) OnConnectAuthenticate(cl *mqtt.Client, pk packets.Packet) bool {
	if cl.Properties.Username == 'david' {
              return true
        }
        return true
}
```

server.go
```go
//something to build the mqtt 
_ = server.AddHook(new(authHook), nil)
//something to start the mqtt 
err := server.Serve()
```

**Comment by dgduncan** [comment]
@TheRiseOfDavid Thank you for your interest in the project! What do you feel is missing in examples such as looking [here](https://github.com/mochi-mqtt/server/blob/main/hooks/auth/auth.go) that could be provided in this new update of the readme?

**Comment by TheRiseOfDavid** [comment]
@dgduncan I feel embarrassed to open this issue. When I was a noob using this package, I didn't realize that `auth.Hook` is an encapsulation of `HookBase`. Because `auth.Hook` is not in the `/example/auth` folder but rather in `hook/auth`, I was confused and thought this project didn't have a hook example. Thank you.
