### ISSUE TITLE
OCSP Stapling support ?

### ISSUE THREAD

**Issue by besrabasant** [mochi-mqtt/server#412]
Is there support for OCSP stapling?

If not, how can I implement my own using hooks?

**Comment by dgduncan** [comment]
I am not super familiar with OCSP stapling but conceptually this involves the initial establishment of the SSL connection by combining the OCSP response and ssl handshake into one request. I believe you will have to use a specific TLS configuration that supports this. If the SSL handshake fails the device shouldn’t even reach the first hook
