### ISSUE TITLE
MQTT bridge

### ISSUE THREAD

**Issue by analystcmyk** [mochi-mqtt/server#414]
I am looking to do the following using a single binary with only CLI params,

Broker1 : publishes to /a/b/c
I  want to subscribe to this topic, and republish to Broker2, using the CLI , to topic /x/y/z

What would be the best way to use mochi for this?

eg `mqtt --republish --in broker1:1883/a/b/c --out Broker2:1883/x/y/z`

Thank you

**Comment by perbu** [comment]
Isn't this exactly what Benthos (Redpanda connect) was made to solve?

**Comment by dgduncan** [comment]
@analystcmyk If you want you can use the internal client and subscribe to the # topic to get a copy of every single message if that works for you.
