### ISSUE TITLE
Is it possible to dynamically remove a hook likewise we add them?

### ISSUE THREAD

**Issue by yusufcanb** [mochi-mqtt/server#415]
Thanks for this incredible implementation. 🤩

I want to be able to remove a hook on runtime. Is it possible somehow?
I didn't see any method as a counter part of the;
```go
err := b.server.AddHook(new(auth.Hook), &auth.Options{
   Ledger: authRules,
})
```

like this;

```go
func RemoveHook(h *auth.Hook)
```

or any other alternatives.

Thanks in advance.

**Comment by dgduncan** [comment]
@yusufcanb at the moment we do not have that functionality. If this is something that is of interest to you please add an issue to the issue sections so it can be tracked :)

**Comment by dgduncan** [comment]
Closing this issue as resolved and next steps is to create an issue
