### ISSUE TITLE
Clients MQTT often experience disconnection  listener=tcp1 error=EOF and i/o timeout

### ISSUE THREAD

**Issue by abdidarmawan007** [mochi-mqtt/server#422]
Clients often experience disconnection

Error logs from mochi server : level=WARN msg="" listener=tcp1 error=EOF and "i/o timeout"

mochi server version : v2.6.4

my config

    listeners:
      - type: "tcp"
        id: "tcp1"
        address: ":1883"
      - type: "ws"
        id: "ws1"
        address: ":1882"
      - type: "sysinfo"
        id: "stats"
        address: ":1880"
    hooks:
      auth:
        allow_all: false
        ledger:
          auth:
            - username: staging-test
              password: xxxxxxxxxxxxx
              allow: true 
    options:
      client_net_write_buffer_size: 2048
      client_net_read_buffer_size: 2048
      sys_topic_resend_interval: 10   
      inline_client: true
    capabilities:
      maximum_client_writes_pending: 8192
      maximum_message_expiry_interval: 14400
      maximum_session_expiry_interval: 86400
      maximum_packet_size: 0
      receive_maximum: 4096
      maximum_inflight: 8192
      topic_alias_maximum: 65535
      shared_sub_available: 1
      minimum_protocol_version: 5
      maximum_qos: 2
      retain_available: 1
      wildcard_sub_available: 1
      sub_id_available: 1
    compatibilities:
      obscure_not_authorized: true
      passive_client_disconnect: false
      always_return_response_info: false
      restore_sys_info_on_restart: false
      no_inherited_properties_on_ack: false
    logging:
      level: INFO

**Comment by thedevop** [comment]
Close issue due to inactivity, reopen if you still experience problem.

**Comment by lucasjinreal** [comment]
time=2025-02-12T23:32:42.352+08:00 level=INFO msg="--> client disconnected" hook=my-hook client=windows_client_wdVM9KPkg expire=false error="server shutting down"
time=2025-02-12T23:32:42.720+08:00 level=INFO msg="mochi mqtt server started"
time=2025-02-12T23:32:51.328+08:00 level=WARN msg="" listener=t1 error="read connection: EOF"
time=2025-02-12T23:32:51.335+08:00 level=WARN msg="" listener=t1 error="server busy"
time=2025-02-12T23:32:51.462+08:00 level=WARN msg="" listener=t1 error="server busy"
time=2025-02-12T23:32:56.521+08:00 level=WARN msg="" listener=t1 error="server busy"
time=2025-02-12T23:34:08.575+08:00 level=WARN msg="" listener=t1 error="server busy"

how to deal with this
