### ISSUE TITLE
【BUG】Server Close() Panic

### ISSUE THREAD

**Issue by wwhai** [mochi-mqtt/server#426]
![image](https://github.com/user-attachments/assets/a252196d-9ae4-414b-8bcd-2edb19409edf)
![image](https://github.com/user-attachments/assets/7d7c1920-b862-42f4-9d37-553b44f18512)

**Comment by thedevop** [comment]
Hi @wwhai , are you using this as an embedded module in your application? If so, check if you're calling the server.Close() more than once.
