### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by jeasonHu** [mochi-mqtt/server#429]
In the process of testing and verifying, found some memory problem;
The following are the test steps
**1**. start server in k8s with 2 pod
**2**. Initiate 2000 connection requests，when execution is complete close test client
**3**. few minutes later  Initiate 3000 connection requests，when execution is complete close test client
**4**.  repeat step 3

The memory usage：
![image](https://github.com/user-attachments/assets/3d33a258-e7a5-480f-ae01-9363eef29ff7)

After performing steps  **2**、**3** Test client has close, all clients has disconnected,bus memory not recovery enough ，causing a backlog; then exec steps  **4**  the memory exceeded the limit, causing the service to restart.

Code:
`github.com/mochi-mqtt/server/v2 v2.6.5`

`
capabilities := mqtt.NewDefaultServerCapabilities()
	capabilities.MaximumSessionExpiryInterval = 60
	capabilities.MaximumInflight = 1024
	capabilities.MaximumClientWritesPending = 256

    mqttServer = mqtt.New(&mqtt.Options{
		Listeners:                nil,
		Hooks:                    nil,
		Capabilities:             capabilities,
		ClientNetWriteBufferSize: 0,
		ClientNetReadBufferSize:  0,
		Logger:                   logger,
		SysTopicResendInterval:   5,
		InlineClient:             true,
	})`

I'm not sure what caused this issue. I made some configuration changes based on the example code.

**Comment by thedevop** [comment]
@jeasonHu, few things:
1. are you clients MQTTv3 or v5?
2. can you verify these clients between step 3 and 4 in fact disconnected from the server? You can check the SysInfo.
3. what's the value set for MaximumMessageExpiryInterval?

Note, setting ClientNetWriteBufferSize and ClientNetReadBufferSize to 0 equals to 2KB.

**Comment by jeasonHu** [comment]
> @jeasonHu, few things:
> 
> 1. are your clients MQTTv3 or v5?
> 2. can you verify these clients between step 3 and 4 in fact disconnected from the server? You can check the SysInfo.
> 3. what's the value set for MaximumMessageExpiryInterval?
> 
> Note, setting ClientNetWriteBufferSize and ClientNetReadBufferSize to 0 equals to 2KB.




1. My client version is v3.  
2. I have confirmed that both `clients_connected` and `clients_total` in `sysinfo` have returned to their initial states.  
3. I set `MaximumMessageExpiryInterval` to 60, and configured `ClientNetWriteBufferSize` and `ClientNetReadBufferSize` to 1024.

**Comment by thedevop** [comment]
If both MaximumMessageExpiryInterval and MaximumSessionExpiryInterval are set to 60, the server should release all the memory used by the clients.

There are 2 other possibilities:
1. Do you have any custom hooks that's holding on the the client?
2. For efficiency reason, Go does not release the freed memory back to OS immediately, you can fine tune this following the [GC-guide](https://tip.golang.org/doc/gc-guide).

**Comment by thedevop** [comment]
@jeasonHu, I hope the above addressed your issue. If not, reopen the issue.
