### ISSUE TITLE
系统topic中有没有设备上线与离线的系统订阅主题？

### ISSUE THREAD

**Issue by xinjiayu** [mochi-mqtt/server#436]
看有系统主题，怎么订阅设备连接与断开连接的topic呢？
例如emqx服务的：
连接：$SYS/brokers/+/clients/+/connected
断开连接：$SYS/brokers/+/clients/+/disconnected

**Comment by kongweitao666** [comment]
大神们，解决了没？  我也很想知道，有没有连接和断开的topic。 还想知道如何去判断设备有没有在线。

**Comment by werbenhu** [comment]
不是有hook钩子吗， 里面有用户的连接，断开连接事件，你自己在事件来的时候发送主题消息就可以了啊

参考：[https://github.com/mochi-mqtt/server/blob/main/examples/hooks/main.go](https://github.com/mochi-mqtt/server/blob/main/examples/hooks/main.go)

**Comment by xinjiayu** [comment]
解析了，是有hooks实现的。
