### ISSUE TITLE
作者你好，我这里出现了不断提示use of closed network connection并且未能稳定重现该异常提示

### ISSUE THREAD

**Issue by Antelope** [mochi-mqtt/server#441]
作者你好，我这里server端出现了不断提示use of closed network connection。该异常会在我的web客户端表现为不断进入client中断及重连成功的钩子，并且该异常无法被稳定重现
![98092B55-6C42-4efb-A3A7-A5419E9D0581](https://github.com/user-attachments/assets/321fecb2-27f6-42b6-b51c-1e53a865979b)

**Comment by Antelope** [comment]
我已经查到问题了，最终发现是前端出现两个client有相同的clientId导致两个clinet互相把对方顶下线

**Comment by ascarl2010** [comment]
怎么配置账号密码
