### ISSUE TITLE
Cluster MQTT broker based on mochi-co/mqtt

### ISSUE THREAD

**Issue by bkupidura** [mochi-mqtt/server#75]
I was looking for cluster ready mqtt broker for my home environment (k8s) for some time already. But unfortunately all i checked (emqx, vernemq) have some issues (e.g not compatible with Paho, or broken in home environment).

So based on `mochi-co/mqtt` i build my own broker - i was heavily inspired by https://github.com/mochi-co/mqtt/pull/45

Maybe other people looking for clustering capabilities will be interested, or even better some pieces can be used inside `mochi-co/mqtt`!

If you think that this is not a place for this kind of communication, please close :)

https://github.com/bkupidura/broker-ha

**Comment by mochi-co** [comment]
Amazing! This is very interesting, and I like what you've done here... I will definitely look into it deeper when I get some time and have a think about how we might implement some of these features in the future :)

**Comment by wind-c** [comment]
Cluster is implemented using gossip and raft protocol. https://github.com/wind-c/comqtt based on mochi-co/mqtt .

**Comment by anthonycorbacho** [comment]
is there any progress on that part? I might be interested :)

**Comment by bkupidura** [comment]
@anthonycorbacho probably you are more interested in clustering capabilities directly in `mochi-co/mqtt`, but i just pushed new version to `bkupidura/broker-ha` which now is based on `mochi-co/mqtt` v2.

**Comment by mochi-co** [comment]
@bkupidura I've been wondering recently if it would be possible to build clustering functionality using the hooks system, but I haven't looked too much into cluster myself. I wonder if it is possible?

**Comment by bkupidura** [comment]
@mochi-co short answer would be yes, it should be possible ;) Currently `broker-ha` is using `mochi-co/mqtt` hooks to forward PUB messages to different members. But my implementation depends on `hashicorp/memberlist`.

Memberlist is used to exchange data between cluster members. It can be replaced by any protocol. Initially i was trying to build this on top of vanilla MQTT. But this approach can be little tricky and complicated with 2+ cluster members.
My initial idea was similar to mosquitto bridge configuration. But this requires mqtt client connected to every broker and syncing state between them over MQTT... Memberlist approach looks much simpler.

You would need to solve 3 main issues:
1) How to discover cluster members?  (DNS SRV discovery in broker-ha)
2) How to handle cluster member join/leave? (memberlist in broker-ha)
2) How to exchange data between cluster members? (memberlist in broker-ha)

**Comment by mochi-co** [comment]
Thanks @bkupidura, I will have a think about this and see if I can come up with any ideas

**Comment by wind-c** [comment]
Comqtt's cluster capability was developed based on mochi-co/mqtt v2.0.
https://github.com/wind-c/comqtt

**Comment by mochi-co** [comment]
This discussion is now located at https://github.com/orgs/mochi-mqtt/discussions/280#discussioncomment-6755488
