### ISSUE TITLE
Please add Authentication and ACL support using MySQL or MongoDB and also installation support on Ubuntu OS

### ISSUE THREAD

**Issue by amin-is** [mochi-mqtt/server#94]
I use Mosquitto as Broker and Go-auth plugin for Authentication and ACL manage using MySQL or MongoDB on ubuntu server. I hope you need to add this type of features. When this type of features will add in your Application i will come back from Mosquitto.

Thanks to make mqtt broker Super Fast application using GO Lang.

**Comment by mochi-co** [comment]
Hi @amin-is! Could you provide an example of how the mysql and mongodb plugins are implemented? It should be trivial for someone who uses either to implement this using the github.com/mochi-co/mqtt/server/listeners/auth Controller interface.

**Comment by wind-c** [comment]
Authentication and ACL support using Redis. May refer to https://github.com/wind-c/comqtt .

**Comment by amin-is** [comment]
@mochi-co 

Very Sorry for late reply.

[Mosquitto Broker](https://github.com/eclipse/mosquitto) is very popular MQTT Broker and [Mosquitto Go Auth](https://github.com/iegomez/mosquitto-go-auth) is a 3rd party  authentication and authorization plugin. Using this plugins i can manage very easily users, password and acls for topis permission. This plugins Support Many popular Database. Currently i am using MongoDB Backend. Also Mosquitto MQTT broker and Mosquitto Go Auth plugins available for many OS Support. But for performance Mochi MQTT is much better. I want to install Mochi MQTT on Ubuntu OS and Mange users authentication and acls control with MongoDB.

Best Regards

**Comment by mochi-co** [comment]
It should be quite simple to make an equivalent of this with the new universal hooks in v2.0.0. If nobody else makes one, I will try to get to it at some point in the future 👍🏻

**Comment by dgduncan** [comment]
@mochi-co I am working on some technology specific hooks along with more general RPC hooks to fulfill this need.

**Comment by dgduncan** [comment]
For anyone interested, here is the very early beginnings of what I am working on: [mochi-cloud-hooks](https://github.com/dgduncan/mochi-cloud-hooks). HTTP is almost done and I am working on `firestore`, `pub/sub`, and `DynamoDB` locally. Please note this is not production ready and is still being actively being worked on.

**Comment by wind-c** [comment]
Comqtt supports multiple authentication ways.
It is developed based on the mochi-co/mqtt v2.0 hook, later it can be pulled out and contributed to mochi-co/mqtt.
https://github.com/wind-c/comqtt

**Comment by dgduncan** [comment]
@mochi-co Should this be closed and moved over to a feature request in our feature roadmap? It seems like less of an issue and more of a feature request.

**Comment by mochi-co** [comment]
@dgduncan Good idea! Let's add this to the roadmap - closing this issue.
